Upgrade to ring-0.16
ewilken/hap-rs pull request #32
Opened 2020-09-09 22:13 UTC by rushidesai

`extract_and_expand` has gone from `ring`. So I had to create some utility functions for this. Not sure where to put them.

2020-09-17 12:51 UTC, ewilken requested changes
Thanks for your contribution! :)

Unfortunately, your `WrappedBuffer` implementation seems to panic on my machine.

Also, the formatting check in CI is complaining. I'm using the nightly `rustfmt` on this project, so a `cargo +nightly fmt` should do the trick.

2020-09-17 12:51 UTC, ewilken commented on src/transport/mod.rs
> +        okm.fill(&mut r).unwrap();
This panicked when I tested the pairing process.
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unspecified', src/transport/mod.rs:25:9
```
Maybe it should rather be a `TryFrom`?

2020-10-16 13:02 UTC, DaleLJefferson commented
I would love to see this PR merged, i'm seeing the same panic.

I'm trying to use `hap` with `rumqttc` and without this PR (upgrade Ring) it does not compile (ring version conflict). 0.13 vs 0.16.

2020-12-13 01:05 UTC, ewilken commented
I just released `v0.1.0-pre.4` that removes the dependency on `ring` entirely in favor of RustCrypto's `hkdf` crate. So this PR is obsoleted and your use case should work now. So closing.

Thanks a lot for caring! Let me know when I can provide any further help!

2020-12-13 01:05 UTC, closed without merging